# Generated by Django 3.1.5 on 2021-03-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('informadoPor', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('tipoAgrupador', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
    ]
