# Generated by Django 3.1.5 on 2021-05-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lattes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('campus', models.CharField(max_length=255)),
                ('tipoVinculo', models.CharField(max_length=255)),
                ('formacao', models.CharField(max_length=255)),
                ('instituicaoEmQueSeFormou', models.CharField(max_length=255)),
                ('anoQueIngressouNoCampus', models.IntegerField()),
            ],
        ),
    ]
