# Generated by Django 3.1.5 on 2021-05-04 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lattes', '0002_pessoas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoas',
        ),
    ]
