# Generated by Django 3.1.5 on 2021-05-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lattes', '0004_pessoas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idCurriculo', models.CharField(max_length=50)),
                ('anoInicio', models.CharField(max_length=4)),
                ('situacao', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('coordenador', models.CharField(max_length=50)),
                ('informadoPor', models.CharField(max_length=50)),
            ],
        ),
    ]
