# Generated by Django 3.1.5 on 2021-07-07 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lattes', '0005_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=45)),
                ('producaoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='lattes.producao')),
            ],
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=45)),
                ('producoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palavrasChave', to='lattes.producao')),
            ],
        ),
    ]
