# Generated by Django 3.1.5 on 2021-07-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lattes', '0006_palavrachave_setoratividade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palavrachave',
            old_name='producoID',
            new_name='producaoID',
        ),
    ]
