# Generated by Django 3.1.5 on 2021-07-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lattes', '0008_areaconhecimento_autor_producaoautor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areaconhecimento',
            old_name='producaID',
            new_name='producao_id',
        ),
        migrations.RenameField(
            model_name='palavrachave',
            old_name='producaoID',
            new_name='producao_id',
        ),
        migrations.RenameField(
            model_name='producaoautor',
            old_name='autor',
            new_name='autor_id',
        ),
        migrations.RenameField(
            model_name='producaoautor',
            old_name='producao',
            new_name='producao_id',
        ),
        migrations.RenameField(
            model_name='setoratividade',
            old_name='producaoID',
            new_name='producao_id',
        ),
    ]
